language: java
sudo: false
script: mvn clean verify
jdk:
- openjdk7
- oraclejdk8
before_deploy:
  - mvn -DfinalName=fact-tools-$TRAVIS_BRANCH package
deploy:
  provider: releases
  api_key:
    secure: GJN2ujMBnMLqnKSLMNq3teVkY8ZtgHiDVBhjNd12PSbnQSNqmLHaAD3Wy0ZWWUHvVqAWeoF7JemJt7x71VHN6/d9jqUktJX4z5Zu/a+gbyeAMsDjPLh3ME5ZDFpEOWg/y8GZ7GwYRkFzRmEY7uE/cD3tH6iPC1fl8tBKQ+YbNI5dhRYkMe/oNO+TgmLQrMCckLEeRSMautWtvQ2XKRZIUFLnJ6Zq4nB+nbaWRJEehHMhAPNsLq9cKPHG55nOtIb+APk6eexV3fnuvC/PidaFQlviW6UUzn8qXPNywt2nCBw3XGOFs8ayJ2bO7m9yAxrY44TJA/eHe8GhonHVf3LojMOGGMrcwjyYcmAeFjGEqvTOeutBi5bs1Agq6t7fGFWuDY6YqM3kTI1/Q6HZ/EE6PjSpuXdAdhKfN4YV75Rf5XFz4FFZ4m5IDRr+7Ya7qmrpQ09vUnzCop6XljfKqJ7DxOo51aAD0w11Z352P4u8IB9/dtUbx8fnEhFzlYbNwjitQX8TWm3/p104VWFTxNNWY8JHS2C2bPRVa4VW5BmYvoXQEwSzYroeEu0ty1mgxphewZvE+jD4uTfMaSsQdO2pR92e18tC2y2lddqOtYOBQ8HiS3GJjfS2a5vi4Y6YOPS10XeyMcmg3K8v04Gecyu5wYaLxYU8lTHWuni3ZW+Cu6w=
  file: target/fact-tools-$TRAVIS_BRANCH.jar
  on:
    tags: true
    repo: fact-project/fact-tools
    java: oraclejdk8
notifications:
  slack:
    secure: IwBFEZoQ5bYquYbOfsVE/EQ6bc6CemwDeCQw1Ok5AryUuj1RvYHBrV1o00kPDi6T2PFuc+jWUTg8VTCTzXUUgJOrjhiBuvYAwEOaDRtCi9uhDHsrPUBLwjB80k2rm90A8RgRd3DDZjxfdz4hHdlsgjFVP/zMCTCvB27vnRMONpejuWQXhTuFhdQqkyzje8s2lGdbtJ7cu7zHuqEn3w5b5J7AbDpwYnbmIZxElgtuJBw3yRkfF5+dmnEIHUKZp+NtffYjW0NEhJQZojP2ea4Qv4qiMv4mwEU3L7ahHNhzz4P9tv3mrjaDHOGcZOk4UuJDW8iNaShvO4RBlWbwWhasahnpg06Oq7YqYzkD85oc+qG5ByKvM1eRn7OyYM9AXuxu1BVncnyz1WKJiuFFTLCnYFD393X/tyjC4iY8MbVhx9NcfhCxFaD6kv6bkAj1ilxs5oMVcthDuLsT/UFQBHM/zMe0zo9AxbWvpyuYToGR5y0UmVCupuQ96jzW9nShmPJtgMuz5jMqki9F6aeBd9e2BGCInBtRBQ1dFpvrqR70Jx+6aiQm//zgVVkfReg0pvJrpYchaG3UIcbI0Kor8+wslmlOY1v0XkJgx1A0BN9m/hRewfPRfn4YR8y7xHHpQRY7AY3j1Ezp8CPRdJ0BzrR2yymAtL8X2bDJZkg64O4BnmM=

