language: java
sudo: false
script: mvn clean verify
jdk:
- oraclejdk8

after_script:
- bash ./deploy_site.sh

env:
  global:
    - GH_REF: github.com/fact-project/fact-tools.git
    - secure: aeSPoJ7VKwYnRpE1mpU02jVNYW3SbRS1UDy2UBt7UZOHOuJ6QzW3ZWaot2M5F4LOHpyvYgpQ//coe4zW/kL6Lf7+M8Xga2cn9Yrqpm03gAZiHLFimPbDuG5WxnRqOPs1kgaWHhlvNXiH5j8bsfWwY52HwyU9aQ7F5tG0xLJnboEwPnb2qy+QkxUqI5u7WFtTd5edAFxtRwFZNLLx1LJ9V+Ej5xl3trVKlvMQ+6QFaUM5lv4TSh/OhEQYJ2IE1tfAadAnqX5CwBDeeVmn7vuYgU7ADXB3MPCYXU2tjsPa4fEi3whCu/62ACb5o8OvCnVRhRB94OvR/v1P8Xh/nTd477eVwV+YV263CEFAHpPjSJsWdYqo+N0UuujebJMpjTP0gdbEoQfGOJH2aek/FEPdOQqqL3c1T6dry12QV6CcTTPLbEMlHBHq/PbeMbcLwBWSbDpYN1ZOhbGW1S7rmjChUGinYC/FOOwrJiwoArLSKkKQiL7HfiufBF4K01s4KtUDoHFprDvWBhc2ZRwZSxZdwFKiGs67i0FEU+g7hjw03WyDftwC9MgkjfDbh7M84DkG6rgcNkqPacIJmKSVJYGYf09BnIRWq8ElaGeAj5gXOfTagAG5BFt8/lSMa7ptete2mC5Oyc4E59sJU4MyOvsumq6Tw1Zjye7gc/bhglrRFJg=

before_deploy:
  - mvn -DfinalName=fact-tools-$TRAVIS_BRANCH package
  - ls target

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kd8coMe1arJPF501mt2UqLypFHSnWsIlCa2CQVpjeGnry/7mMSRGz8fGNCAQ3/nT1TX+8duys2dh1kvP3GUMACLY5g/7uQScvwbGwH7mIWIVHCuriJdfvAL3gN72792u/OXb4tabVKuGzx6Qx6mCzZqX5k4tKGFfm9ZYqTr+i6qc5L1q9X8wZaCT5yoQI/H+puaiMCiZObWdeA+U9BsA5DSgPV8Jqexz2tT9OG5T42D8xSR5Z9CMZCEoGHDoxgZn74vC858tvQS5fk90GkGm7IzaRc0mWcTQ9yZGW9jmLFV7A00NtC2G+f3SIn1cCjHwYggwZFBYcr+83zmmeMRY87N96wrogsUhTFEGN/zG5nwhb+umcmaHthuH/2ZQeQ1hDc6kfF+2q3IpTZcrdqxItUDYFMxWycUCnGCLi6be85fZlEwiylbmsrlMs+jfbOgo1fcFQFuo27VvSWtD0u+5Vsngk91WqnWZIoFZM0wb8LMhw47cBOyjerhe4VQ+vShSv/zGa+g8Irr0GITGEfJOd84VbXTXIZ0mtOUu295hjxwwBbMCmdRTdQLWcBtYB4J9oHVHwno+lV65OKuynBHnrRVge0ZOSrmuzLpTWBjsaao29E34bwiVr0kCFjq/ThHTyZiH5gLXNj0QdS7nFytvtV3ggdzyWML8FHX2cWEdzo0=
  file: target/fact-tools-$TRAVIS_BRANCH.jar
  on:
    tags: true
    repo: fact-project/fact-tools
    java: oraclejdk8

notifications:
  slack:
    secure: IwBFEZoQ5bYquYbOfsVE/EQ6bc6CemwDeCQw1Ok5AryUuj1RvYHBrV1o00kPDi6T2PFuc+jWUTg8VTCTzXUUgJOrjhiBuvYAwEOaDRtCi9uhDHsrPUBLwjB80k2rm90A8RgRd3DDZjxfdz4hHdlsgjFVP/zMCTCvB27vnRMONpejuWQXhTuFhdQqkyzje8s2lGdbtJ7cu7zHuqEn3w5b5J7AbDpwYnbmIZxElgtuJBw3yRkfF5+dmnEIHUKZp+NtffYjW0NEhJQZojP2ea4Qv4qiMv4mwEU3L7ahHNhzz4P9tv3mrjaDHOGcZOk4UuJDW8iNaShvO4RBlWbwWhasahnpg06Oq7YqYzkD85oc+qG5ByKvM1eRn7OyYM9AXuxu1BVncnyz1WKJiuFFTLCnYFD393X/tyjC4iY8MbVhx9NcfhCxFaD6kv6bkAj1ilxs5oMVcthDuLsT/UFQBHM/zMe0zo9AxbWvpyuYToGR5y0UmVCupuQ96jzW9nShmPJtgMuz5jMqki9F6aeBd9e2BGCInBtRBQ1dFpvrqR70Jx+6aiQm//zgVVkfReg0pvJrpYchaG3UIcbI0Kor8+wslmlOY1v0XkJgx1A0BN9m/hRewfPRfn4YR8y7xHHpQRY7AY3j1Ezp8CPRdJ0BzrR2yymAtL8X2bDJZkg64O4BnmM=
