language: java
sudo: false
script: mvn clean verify
jdk:
- openjdk7
- oraclejdk8
after_script:
- bash ./deploy_site.sh
env:
  global:
    - GH_REF: github.com/fact-project/fact-tools.git
    - secure: aeSPoJ7VKwYnRpE1mpU02jVNYW3SbRS1UDy2UBt7UZOHOuJ6QzW3ZWaot2M5F4LOHpyvYgpQ//coe4zW/kL6Lf7+M8Xga2cn9Yrqpm03gAZiHLFimPbDuG5WxnRqOPs1kgaWHhlvNXiH5j8bsfWwY52HwyU9aQ7F5tG0xLJnboEwPnb2qy+QkxUqI5u7WFtTd5edAFxtRwFZNLLx1LJ9V+Ej5xl3trVKlvMQ+6QFaUM5lv4TSh/OhEQYJ2IE1tfAadAnqX5CwBDeeVmn7vuYgU7ADXB3MPCYXU2tjsPa4fEi3whCu/62ACb5o8OvCnVRhRB94OvR/v1P8Xh/nTd477eVwV+YV263CEFAHpPjSJsWdYqo+N0UuujebJMpjTP0gdbEoQfGOJH2aek/FEPdOQqqL3c1T6dry12QV6CcTTPLbEMlHBHq/PbeMbcLwBWSbDpYN1ZOhbGW1S7rmjChUGinYC/FOOwrJiwoArLSKkKQiL7HfiufBF4K01s4KtUDoHFprDvWBhc2ZRwZSxZdwFKiGs67i0FEU+g7hjw03WyDftwC9MgkjfDbh7M84DkG6rgcNkqPacIJmKSVJYGYf09BnIRWq8ElaGeAj5gXOfTagAG5BFt8/lSMa7ptete2mC5Oyc4E59sJU4MyOvsumq6Tw1Zjye7gc/bhglrRFJg=
deploy:
  provider: releases
  api_key:
    secure: GJN2ujMBnMLqnKSLMNq3teVkY8ZtgHiDVBhjNd12PSbnQSNqmLHaAD3Wy0ZWWUHvVqAWeoF7JemJt7x71VHN6/d9jqUktJX4z5Zu/a+gbyeAMsDjPLh3ME5ZDFpEOWg/y8GZ7GwYRkFzRmEY7uE/cD3tH6iPC1fl8tBKQ+YbNI5dhRYkMe/oNO+TgmLQrMCckLEeRSMautWtvQ2XKRZIUFLnJ6Zq4nB+nbaWRJEehHMhAPNsLq9cKPHG55nOtIb+APk6eexV3fnuvC/PidaFQlviW6UUzn8qXPNywt2nCBw3XGOFs8ayJ2bO7m9yAxrY44TJA/eHe8GhonHVf3LojMOGGMrcwjyYcmAeFjGEqvTOeutBi5bs1Agq6t7fGFWuDY6YqM3kTI1/Q6HZ/EE6PjSpuXdAdhKfN4YV75Rf5XFz4FFZ4m5IDRr+7Ya7qmrpQ09vUnzCop6XljfKqJ7DxOo51aAD0w11Z352P4u8IB9/dtUbx8fnEhFzlYbNwjitQX8TWm3/p104VWFTxNNWY8JHS2C2bPRVa4VW5BmYvoXQEwSzYroeEu0ty1mgxphewZvE+jD4uTfMaSsQdO2pR92e18tC2y2lddqOtYOBQ8HiS3GJjfS2a5vi4Y6YOPS10XeyMcmg3K8v04Gecyu5wYaLxYU8lTHWuni3ZW+Cu6w=
  file: target/fact-tools-$TRAVIS_BRANCH.jar
  on:
    tags: true
    repo: fact-project/fact-tools
