language: java
sudo: false
script: mvn clean verify
jdk:
- openjdk7
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: GJN2ujMBnMLqnKSLMNq3teVkY8ZtgHiDVBhjNd12PSbnQSNqmLHaAD3Wy0ZWWUHvVqAWeoF7JemJt7x71VHN6/d9jqUktJX4z5Zu/a+gbyeAMsDjPLh3ME5ZDFpEOWg/y8GZ7GwYRkFzRmEY7uE/cD3tH6iPC1fl8tBKQ+YbNI5dhRYkMe/oNO+TgmLQrMCckLEeRSMautWtvQ2XKRZIUFLnJ6Zq4nB+nbaWRJEehHMhAPNsLq9cKPHG55nOtIb+APk6eexV3fnuvC/PidaFQlviW6UUzn8qXPNywt2nCBw3XGOFs8ayJ2bO7m9yAxrY44TJA/eHe8GhonHVf3LojMOGGMrcwjyYcmAeFjGEqvTOeutBi5bs1Agq6t7fGFWuDY6YqM3kTI1/Q6HZ/EE6PjSpuXdAdhKfN4YV75Rf5XFz4FFZ4m5IDRr+7Ya7qmrpQ09vUnzCop6XljfKqJ7DxOo51aAD0w11Z352P4u8IB9/dtUbx8fnEhFzlYbNwjitQX8TWm3/p104VWFTxNNWY8JHS2C2bPRVa4VW5BmYvoXQEwSzYroeEu0ty1mgxphewZvE+jD4uTfMaSsQdO2pR92e18tC2y2lddqOtYOBQ8HiS3GJjfS2a5vi4Y6YOPS10XeyMcmg3K8v04Gecyu5wYaLxYU8lTHWuni3ZW+Cu6w=
  file: target/fact-tools-*.jar
  on:
    repo: fact-project/fact-tools
