/**
 * This class is generated by jOOQ
 */
package fact.rta.persistence;


import fact.rta.persistence.tables.Signal;
import fact.rta.persistence.tables.Sources;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table signal
	 */
	public static final Signal SIGNAL = fact.rta.persistence.tables.Signal.SIGNAL;

	/**
	 * The table sources
	 */
	public static final Sources SOURCES = fact.rta.persistence.tables.Sources.SOURCES;
}
